### PR TITLE
Add file argument; change file in place

### PR DESCRIPTION
**Pull request by bieron**
Hello,

thanks for this neat little script. I've made it so it you can use it without stream redirection and moving one file over another. Hope you find this addition useful! Feel free to modify something if you don't agree with everything.

Cheers,
bieron

### CODE REVIEW

**Comment by quentinsf** [comment]
Hi Bieron - and sorry, I thought I'd responded to this earlier, but it looks as if I forgot!

I like the option to update the file in place, but I think I'd use a slightly different syntax: the _modernize_ and _futurize_ utilities both (I think) allow you to specify the file as an argument, and they output the changed version to stdout.  If you want the input file to be modified in place, you add a '-w' option.

Can I suggest that, just because it seems to be becoming a bit more of a standard for tools which modify Python source code?

All the best, 
Quentin

**Comment by bieron** [comment]
Interesting, I was not aware of such trend.
Could you give me examples of such tools that use modernize/futurize and the -w option?

**Comment by quentinsf** [comment]
Hi there - 

Sure - here's the documentation [for Modernize](https://python-modernize.readthedocs.io/en/latest/) and [for Futurize](http://python-future.org/automatic_conversion.html#futurize-quick-start-guide).  

They both use the '-w' convention, perhaps because [2to3](https://docs.python.org/2/library/2to3.html) also uses it.

Lots of other utilities do different things, of course, but I think that if something normally just analyses a file, you should probably be required to specify an explicit option if you want it to _change_ the file too. This script seems to fit in with these other utilities, so I suggested '-w'.  What do you think?

Best,
Quentin

**Comment by bieron** [comment]
Thanks for the prompt release!

**Pull request merged**
